### ISSUE TITLE
Missing include files when attempting to build on Win64

### ISSUE THREAD

**Issue by sipsorcery** [erikuhlmann/ntcore_node#1]
The following line fails:

node-gyp configure build --python "C:\Python27"

Opening the solution file up in VS 2015 shows two missing include files in ntcore_node.cc
# include "ntcore.h"
# include "networktables/NetworkTable.h"

Whereabouts should they be located?

**Comment by xeniarose** [comment]
[`ntcore/include`](https://github.com/erikuhlmann/ntcore_node/blob/master/binding.gyp#L11)

make sure to `git submodule init pull` to set up the [ntcore](https://github.com/wpilibsuite/ntcore) submodule in this repo.

**Comment by xeniarose** [comment]
Did this solve your issue? I will close this for now, unless you post back.
